// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.softfn.demo.ice.test;

public interface MyService extends Ice.Object,
                                   _MyServiceOperations, _MyServiceOperationsNC
{
    public static final String ice_staticId = "::test::MyService";

    public static final long serialVersionUID = 4192581273415399618L;
}
